### ISSUE TITLE
Use GIS keywords to determine posting frequency

### ISSUE THREAD

**Issue by kdwarn** [dvrpc/ckanext-dvrpc_gis_harvester#2]
Default will be "as_needed".

Two keywords to be added - weekly and biannually - to be used for this field if they exist on the GIS database.

**Comment by seandoesgis** [comment]
Added 3 test keywords (Daily) to Traffic Counts, Bicycle Counts, Pedestrian Counts.  At this point there aren't a lot of other weekly/bi-annual/quarterly/annually datasets really.

**Comment by kdwarn** [comment]
@seandoesgis Those worked, so you can remove them if they were just for testing.
