### ISSUE TITLE
Use GIS categories/subcategories for CKAN categories

### ISSUE THREAD

**Issue by kdwarn** [dvrpc/ckanext-dvrpc_gis_harvester#3]
To be added to the GIS DCAT.

**Comment by seandoesgis** [comment]
Added to GIS DCAT as "theme".  Use this translation to bridge the 2:

GIS Category | GIS Sub Categories | CKAN Relationship
-- | -- | --
Biota |   | Environment
Boundaries |   | Boundaries
Demographics | Equity and Diversity | Demographics & Housing, Equity & Diversity
Economy |   | Economy
Environment |   | Environment
Freight |   | Freight & Aviation
Geology |   | Environment
Hydrology |   | Environment
Imagery and Elevation |   | Imagery
Location |   | Boundaries
Parcels |   | Planning
Planning | Long-Range Plan | Planning, Long-Range Plan
Structures |   | Planning
Transportation | Bicycle and Pedestrian, Highway, TIP, Transit, Safety and Health | Bicycle & Pedestrian, Highway, TIP, Transit, Safety & Health
Utilities |   | Environment


</body>
</html>

**Comment by kdwarn** [comment]
Closed with 2f9951c.
