### ISSUE TITLE
Get CKAN agency_owner from GIS "agency" field

### ISSUE THREAD

**Issue by kdwarn** [dvrpc/ckanext-dvrpc_gis_harvester#4]
On the GIS side, this field will be more structured in order to pull information from it, e.g. 

<strike>"Agency Owners: NJDOT, PennDOT"

or

"Agency Owners: SEPTA"</strike>

Not going into "accessInformation" field. New field created - "agency".

This also first depends on https://github.com/dvrpc/ckanext-dvrpc_theme/issues/6

**Comment by seandoesgis** [comment]
Added "agency" to GIS DCAT.  Following standardized list in [metadata (CKAN schema) / MetadataDomainValues tab](https://docs.google.com/spreadsheets/d/1KWzLzl-AbJvLqz2-wcxJ7HeBvFImEazd0EOY0lm7nr8/edit?usp=sharing) and adding more as I standardize each dataset.  List is growing.

**Comment by kdwarn** [comment]
Wait until standardization is complete to implement this.

**Comment by seandoesgis** [comment]
All GIS data has standardized agency values. 🙂

**Comment by kdwarn** [comment]
note to self: "agency" branch

**Comment by kdwarn** [comment]
Waiting on decision re: full names or acronyms or full name (acronym)

**Comment by kdwarn** [comment]
Agree to use Full name (Acronym) [ex: "New Jersey Department of Transportation (NJDOT)"] (from gchat on Feb 18, 2022).
